# Generated by Django 2.1.7 on 2019-03-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
