# Generated by Django 2.1.7 on 2019-03-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20190320_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.FilePathField(match='bo.jpg', path='/static/image/poster'),
        ),
    ]
