# Generated by Django 2.1.7 on 2019-03-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_auto_20190320_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cut_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='short_comment',
            field=models.TextField(blank=True),
        ),
    ]
