# Generated by Django 2.1.7 on 2019-03-26 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_auto_20190326_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_file', models.FilePathField(blank=True, path='C:/Users/lzr/analysis_web/static/comment/original')),
                ('comment_cut_file', models.FilePathField(blank=True, path='C:/Users/lzr/analysis_web/static/comment/seg')),
                ('stop_word_file', models.FilePathField(blank=True, path='C:/Users/lzr/analysis_web/static/comment/stop_word')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Movie')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='cut_comment',
        ),
    ]
